# Copyright (c) 2025 Charles P44
# SPDX-License-Identifier: MIT
export_to_csv:
  name: Exporter les données en CSV (Standard)
  description: "Exporte une plage de données historiques dans des fichiers CSV bruts."
  fields:
    device:
      name: Appareil Beem
      description: "Sélectionnez l'appareil Beem Energy concerné."
      selector:
        device:
          integration: beem_energy
    start_date:
      name: Date de début
      description: "La première journée à inclure dans l'export."
      required: true
      selector:
        date:
    end_date:
      name: Date de fin
      description: "La dernière journée à inclure dans l'export."
      required: true
      selector:
        date:

export_for_import:
  name: Exporter pour importation (Générique)
  description: "Exporte les données dans un format CSV cumulatif avec un ID de statistique générique (beem_energy:...). Utile pour des outils externes."
  fields:
    device:
      name: Appareil Beem
      description: "Sélectionnez l'appareil Beem Energy concerné."
      selector:
        device:
          integration: beem_energy
    start_date:
      name: Date de début
      required: true
      selector:
        date:
    end_date:
      name: Date de fin
      required: true
      selector:
        date:

export_for_ha_import:
  name: Exporter pour réimportation HA (Avancé)
  description: "Exporte les données en utilisant les IDs des capteurs existants. ATTENTION : Pour utilisateurs avancés voulant remplir l'historique de capteurs spécifiques."
  fields:
    device:
      name: Appareil Beem
      description: "Sélectionnez l'appareil Beem Energy concerné."
      selector:
        device:
          integration: beem_energy
    start_date:
      name: Date de début
      required: true
      selector:
        date:
    end_date:
      name: Date de fin
      required: true
      selector:
        date:

import_statistic:
  name: Importer des statistiques depuis un fichier
  description: "Importe des statistiques depuis un fichier CSV placé dans le dossier /config."
  fields:
    filename:
      name: Nom du fichier
      description: "Le chemin du fichier depuis le dossier /config (ex: 'mon_import.csv')."
      required: true
      selector:
        text:

import_ha_statistics_files:
  name: Importer tous les fichiers d'historique HA
  description: "Recherche et importe automatiquement tous les fichiers CSV générés par le service 'export_for_ha_import' qui se trouvent dans le dossier /config/www/beem_exports."
